default:
  NAME: MadMachine
  DEBUG: true

  # 编辑窗口
  EDIT_WINDOW:
    URL: http://localhost:8080/edit.html

  # 设置窗口
  SETTING_WINDOW:
    URL: http://localhost:8080/setting.html

  # 串口通讯窗口
  SERIAL_WINDOW:
    URL: http://localhost:8080/serial.html

  # 用户登录窗口
  USER_WINDOW:
    URL: http://localhost:8080/user.html

  # 关于MadMachine
  ABOUT_WINDOW:
    URL: http://localhost:8080/about.html

  # 启动页面
  START_WINDOW:
    URL: http://localhost:8080/start.html

  USB:
    NAME: SWIFTIO
