default:
  NAME: MadMachine

  # 编辑窗口
  EDIT_WINDOW:
    WIDTH: 1200
    HEIGHT: 800

  # 主题
  THEME:
    NAME: black
    STYLE:
      BLACK:
        BG_COLOR: '"#45475f"'
      WHITE:
        BG_COLOR: '"#ececec"'

  EDITER:
    FONTSIZE: 12

  # 文件管理配置
  FILEMANAGER:
    SYNC_TIME: 1000
